name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main
  schedule:
    # run every Monday at 5am UTC
    - cron: '0 5 * * 1'

jobs:
  ##########
  # Until GA supports step reuse/inheritance or better conditional
  # exclusion of matrix targets, this is the shortest way of creating
  # our matrix. It's not best because of some duplication and manual
  # cranking, but other options require much more duplication.
  ##########
  tests:
    name: ${{ matrix.target.env }} (${{ matrix.target.os }})
    runs-on: ${{ matrix.target.os }}
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        target: [
        {"os": "macos-latest",   "python": "3.9", "env": "py3.9-test"},
        {"os": "windows-latest", "python": "3.9", "env": "py3.9-test"},
        {"os": "ubuntu-latest",  "python": "3.9", "env": "py3.9-test"},
        {"os": "ubuntu-latest",  "python": "3.8", "env": "py3.8-test"},
        {"os": "ubuntu-latest",  "python": "3.7", "env": "py3.7-test"},
        {"os": "ubuntu-latest",  "python": "3.6", "env": "py3.6-test"}
        ]
        include:
          - toxargs: -v
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.target.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install newest astro_metadata_translator
        run: |
          git clone https://github.com/lsst/astro_metadata_translator.git
          python astro_metadata_translator/setup.py
      - name: Run tests
        run: |
          python trail/manage.py test -v2 -b
